export const homeRoute = "/";
export const enochAssistantRoute = "/enoch";
export const workspaceRoute = "/workspace";
export const dashboardRoute = "/dashboard";
export const sequenceRoute = "/sequence";
export const studioRoute = "/studio";
export const projectsRoute = "/projects";
export const loginRoute = "/login";
export const newProjectRoute = `${projectsRoute}/new`;
export const enochPlanRoute = "/enoch/plan";
export const accountRoute = "/account";
export const projectRoute = (projectId: string) => `/projects/${projectId}`;
export const sequenceRouteForProject = (projectId: string) => `${sequenceRoute}?projectId=${encodeURIComponent(projectId)}`;
export const projectEnochRoute = (projectId: string) => `${projectRoute(projectId)}/enoch`;
export const sceneReviewRoute = (projectId: string) => `${projectRoute(projectId)}/scenes`;
export const clipReviewRoute = (projectId: string) => `${projectRoute(projectId)}/clips`;
export const renderRoute = (projectId: string) => `${projectRoute(projectId)}/render`;
export const publishRoute = (projectId: string) => `${projectRoute(projectId)}/publish`;
